/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticketbooking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;

/**
 *
 * @author wanas
 */
public class RomanceList extends javax.swing.JFrame {
    
    Connection myConn;
    Statement myStmt;
    ResultSet myRs;
    PreparedStatement pstmt;

    String address = "jdbc:mysql://localhost:3306/movieticketing";
    String user = "root";
    String pass = "";
    
    /**
     * Creates new form RomanceList
     */
    public RomanceList() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        choice1 = new javax.swing.JLabel();
        choice2 = new javax.swing.JLabel();
        choice3 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        duration1 = new javax.swing.JLabel();
        duration2 = new javax.swing.JLabel();
        duration3 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Romance Films");

        choice1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice1.setText("1");

        choice2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice2.setText("2");

        choice3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice3.setText("3");

        title1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title1.setText("title1");

        title2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title2.setText("title2");

        title3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title3.setText("title3");

        jButton1.setText("Show Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        duration1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration1.setText("duration1");

        duration2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration2.setText("duration2");

        duration3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration3.setText("duration3");

        price1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        price1.setText("price1");

        price2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        price2.setText("price2");

        price3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        price3.setText("price3");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie 1", "Movie 2", "Movie 3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose Movie :");

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choice2)
                                    .addComponent(choice1)
                                    .addComponent(choice3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title3)
                                    .addComponent(title2)
                                    .addComponent(title1))
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duration2)
                                    .addComponent(duration3)
                                    .addComponent(duration1))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price1)
                                    .addComponent(price3)
                                    .addComponent(price2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choice1)
                            .addComponent(title1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choice2)
                            .addComponent(title2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choice3)
                            .addComponent(title3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(duration1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duration2)
                        .addGap(11, 11, 11)
                        .addComponent(duration3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price2)
                        .addGap(11, 11, 11)
                        .addComponent(price3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Show database
        
        String[] title = new String[3];
        double[] duration = new double[3];
        String[] movCode = new String[3];
        double[] price = new double[3];
        int movChoice;
        
        String SQL = "SELECT * FROM romance";
        try
        {
            //connect to database
            myConn = DriverManager.getConnection(address, user, pass);
            myStmt = myConn.createStatement();
            
            //checking
            myRs = myStmt.executeQuery(SQL);
            
            int i = 0;
            while (myRs.next())
            {
                title[i] = myRs.getString(1);
                duration[i] = myRs.getDouble(2);
                movCode[i] = myRs.getString(3);
                price[i] = myRs.getDouble(4);
                i++;
            }
            
            String d1 = Double.toString(duration[0]);
            String d2 = Double.toString(duration[1]);
            String d3 = Double.toString(duration[2]);
            
            String p1 = Double.toString(price[0]);
            String p2 = Double.toString(price[1]);
            String p3 = Double.toString(price[2]);
            
            title1.setText(title[0]);
            title2.setText(title[1]);
            title3.setText(title[2]);
            
            duration1.setText(d1);
            duration2.setText(d2);
            duration3.setText(d3);
            
            price1.setText(p1);
            price2.setText(p2);
            price3.setText(p3);
                            
        }catch (Exception e)
        {
            System.out.println("Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Back
        this.dispose();
        new GenreMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Movie Choice
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Next
        
        String SQL1 = "INSERT INTO bookings (ticketID, movie,price) VALUES (?,?,?)";
        String SQL2 = "SELECT * FROM romance";
        String movie = null;
        String id = null;
        double price = 0;
        
        Random rand = new Random();
        int upperbound = 100;
        int intRandom = rand.nextInt(upperbound);
        
        String movChoice = (String)jComboBox1.getSelectedItem();
        
        try
        {
            //connect to database
            myConn = DriverManager.getConnection(address, user, pass);
            myStmt = myConn.createStatement();
            
            myRs = myStmt.executeQuery(SQL2);
            pstmt = myConn.prepareStatement(SQL1);
            int i = 0;
            
            while (myRs.next())
            {
                if (movChoice.equals("Movie " + (i=i+1)))
                {
                    movie = myRs.getString(1);
                    id = myRs.getString(3) + intRandom;
                    price = myRs.getDouble(4);
                    pstmt.setString(1,id);
                    pstmt.setString(2, movie);
                    pstmt.setDouble(3,price);
                    pstmt.executeUpdate();
                    break;
                }
            }
            
        }catch (Exception e) {System.out.println("Error"); e.printStackTrace();}
        
        this.dispose();
        new seating().setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RomanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RomanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RomanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RomanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RomanceList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choice1;
    private javax.swing.JLabel choice2;
    private javax.swing.JLabel choice3;
    private javax.swing.JLabel duration1;
    private javax.swing.JLabel duration2;
    private javax.swing.JLabel duration3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
